[package]
name = "codeowners_rs"
version = "0.1.0"
edition = "2021"
authors = ["Reid Lynch <reid.lynch@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.8.2" }
